backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "docs/images"
public_folder: "/images" 
collections:
  - name: "posts"
    label: "Posts"
    folder: "docs/posts"
    slug: "{{slug}}"
    preview_path: "posts/{{slug}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm", format: "LLL"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Tags", name: "tags", widget: "select", multiple: true, options: ["beer", "food", "music", "movies", "sports", "other"]}
      - {label: "shorty", name: "shorty", widget: "boolean", hint: "A shorty is one you want to show the whole post on the homepage.", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
