backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "docs/images"
public_folder: "/images" 
collections:
  - name: "posts"
    label: "Posts"
    folder: "docs/posts"
    slug: "{{slug}}"
    preview_path: "posts/{{slug}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Date", name: "date", widget: "datetime", required: true}
      - {label: "Author", name: "author", widget: "string", required: true}
      - {label: "Tags", name: "tags", widget: "select", multiple: true, options: ["beer", "food", "music", "movies", "sports", "other"], required: true}
      - {label: "Body", name: "body", widget: "markdown", required: true}
