backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "images"
collections:
  - name: "posts"
    label: "Posts"
    folder: "docs/posts"
    slug: "{{slug}}"
    preview_path: "posts/{{slug}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list", allow_add: true}
      - {label: "Body", name: "body", widget: "markdown"}